# Fundamentos de Python para Análise de Dados

## Introdução às bibliotecas NumPy, Pandas e Matplotlib

Neste notebook, vamos explorar as principais bibliotecas utilizadas para análise de dados em Python:

1. **NumPy**: Biblioteca fundamental para computação científica em Python
2. **Pandas**: Biblioteca para manipulação e análise de dados estruturados
3. **Matplotlib**: Biblioteca para visualização de dados

Estas três bibliotecas formam a base do ecossistema de análise de dados em Python e são essenciais para qualquer projeto de Big Data.

## 1. NumPy (Numerical Python)

NumPy é a biblioteca fundamental para computação científica em Python. Ela fornece:

- Arrays multidimensionais eficientes
- Funções matemáticas para operar nesses arrays
- Ferramentas para integração com outras linguagens como C/C++ e Fortran

Vamos começar importando a biblioteca e explorando suas funcionalidades básicas.

### Instalação
Para instalar o NumPy, você pode usar pip:

In [ ]:
# % pip install numpy

### 2. Arrays NumPy
O objeto central do NumPy é o array n-dimensional, chamado ndarray. Vamos ver como criar arrays:

In [1]:
# Importando a biblioteca NumPy
import numpy as np

In [2]:
# Criar array a partir de uma lista
array_1d = np.array([1, 2, 3, 4, 5])
print(array_1d)  # [1 2 3 4 5]

[1 2 3 4 5]


In [3]:
# Array bidimensional (matriz)
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d)

[[1 2 3]
 [4 5 6]]


In [4]:


# Criando um array NumPy
arr = np.array([1, 2, 3, 4, 5])
print("Array NumPy:", arr)
print("Tipo do array:", type(arr))

Array NumPy: [1 2 3 4 5]
Tipo do array: <class 'numpy.ndarray'>


### 1.1 Criando Arrays NumPy

In [5]:
# Criando arrays com diferentes funções
zeros = np.zeros(50)  # Array de zeros
# print("Array de zeros:", zeros)

zeros[0:10]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
ones = np.ones(10)    # Array de uns
print(ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [7]:
arange = np.arange(0, 50, 2)  # Array com valores em um intervalo especificado
print(arange)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]


In [9]:
linspace = np.linspace(0, 50, 50)  # Array com valores linearmente espaçados
print(linspace)



[ 0.          1.02040816  2.04081633  3.06122449  4.08163265  5.10204082
  6.12244898  7.14285714  8.16326531  9.18367347 10.20408163 11.2244898
 12.24489796 13.26530612 14.28571429 15.30612245 16.32653061 17.34693878
 18.36734694 19.3877551  20.40816327 21.42857143 22.44897959 23.46938776
 24.48979592 25.51020408 26.53061224 27.55102041 28.57142857 29.59183673
 30.6122449  31.63265306 32.65306122 33.67346939 34.69387755 35.71428571
 36.73469388 37.75510204 38.7755102  39.79591837 40.81632653 41.83673469
 42.85714286 43.87755102 44.89795918 45.91836735 46.93877551 47.95918367
 48.97959184 50.        ]


In [10]:
identity = np.eye(5)      # Matriz identidade 3x3
print(identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [11]:
identity = np.eye(10)      # Matriz identidade 4x4
print(identity)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [12]:

random_array = np.random.random((2, 2))  # Valores aleatórios entre 0 e 1
print(random_array)

[[0.26270589 0.76378593]
 [0.85690204 0.20356752]]


### 4. Operações básicas

In [14]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Operações aritméticas são elemento a elemento
print(a + b)  # [5 7 9]
print(a * b)  # [4 10 18]
print(a ** 2) # [1 4 9]

# Comparações também são elemento a elemento
print(a < 3)  # [True True False]

[5 7 9]
[ 4 10 18]
[1 4 9]
[ True  True False]


### 5. Indexação e fatiamento

In [25]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

array[3:5]

array([4, 5])

In [15]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [16]:
# Acessar elemento
print(arr[0,0])  # 2

1


In [17]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
# Fatiar linhas e colunas
print(arr[0:2, 1:3])

[[2 3]
 [6 7]]


In [26]:

# Indexação booleana
print(arr[arr > 5])  # [6 7 8 9 10 11 12]

[ 6  7  8  9 10 11 12]


### 6. Estatísticas

In [27]:
data = np.array([1, 2, 3, 4, 5])

print(np.mean(data))      # 3.0
print(np.median(data))    # 3.0
print(np.std(data))       # Desvio padrão
print(np.var(data))       # Variância
print(np.min(data))       # 1
print(np.max(data))       # 5
print(np.sum(data))       # 15

3.0
3.0
1.4142135623730951
2.0
1
5
15


### 7. Reshape e redimensionamento

In [28]:
arr = np.arange(12)  # [0 1 2 3 4 5 6 7 8 9 10 11]
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [29]:
# Reshape para 3x4
reshaped = arr.reshape(3, 4)
print(reshaped)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [30]:
# Transposta
transposed = reshaped.T
print(transposed)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


### 8. Broadcasting
O broadcasting permite que o NumPy trabalhe com arrays de diferentes formas quando realiza operações aritméticas:

In [31]:
a = np.array([[1, 2, 3], [4, 5, 6]])  # forma (2, 3)
b = np.array([10, 20, 30])            # forma (3,)

# b é automaticamente expandido para forma (2, 3)
print(a + b)
# [[11 22 33]
#  [14 25 36]]

[[11 22 33]
 [14 25 36]]


## Aplicações práticas do NumPy na vida real
### O NumPy tem aplicações em inúmeros campos devido à sua capacidade de processar grandes volumes de dados com eficiência. 
### Exemplo prático de análise de dados meteorológicos, algo relevante para diversos setores como agricultura, planejamento urbano e previsão do tempo.

### Análise de dados de temperatura

#### Imagine que você trabalha para uma empresa agrícola e precisa analisar dados de temperatura para otimizar o plantio. Você tem medições diárias de temperatura ao longo de um ano.

In [32]:
#explique o linspace
dias = 365
np.linspace(0, 2 * np.pi, dias)

array([0.        , 0.0172615 , 0.034523  , 0.05178449, 0.06904599,
       0.08630749, 0.10356899, 0.12083049, 0.13809198, 0.15535348,
       0.17261498, 0.18987648, 0.20713798, 0.22439948, 0.24166097,
       0.25892247, 0.27618397, 0.29344547, 0.31070697, 0.32796846,
       0.34522996, 0.36249146, 0.37975296, 0.39701446, 0.41427595,
       0.43153745, 0.44879895, 0.46606045, 0.48332195, 0.50058344,
       0.51784494, 0.53510644, 0.55236794, 0.56962944, 0.58689094,
       0.60415243, 0.62141393, 0.63867543, 0.65593693, 0.67319843,
       0.69045992, 0.70772142, 0.72498292, 0.74224442, 0.75950592,
       0.77676741, 0.79402891, 0.81129041, 0.82855191, 0.84581341,
       0.8630749 , 0.8803364 , 0.8975979 , 0.9148594 , 0.9321209 ,
       0.9493824 , 0.96664389, 0.98390539, 1.00116689, 1.01842839,
       1.03568989, 1.05295138, 1.07021288, 1.08747438, 1.10473588,
       1.12199738, 1.13925887, 1.15652037, 1.17378187, 1.19104337,
       1.20830487, 1.22556636, 1.24282786, 1.26008936, 1.27735

In [41]:
import numpy as np
import matplotlib.pyplot as plt  # Para visualização

# Simular dados diários de temperatura (em Celsius) para um ano
dias = 365
np.random.seed(42)  # Para reprodutibilidade
temperaturas = 20 + 10 * np.sin(np.linspace(0, 2*np.pi, dias)) + np.random.normal(0, 3, dias)

# Converter dados para array NumPy
temp_array = np.array(temperaturas)

# Análise básica
temperatura_media = np.mean(temp_array)
temperatura_maxima = np.max(temp_array)
temperatura_minima = np.min(temp_array)
temperatura_desv_padrao = np.std(temp_array)

print(f"Temperatura média: {temperatura_media:.1f}°C")
print(f"Temperatura máxima: {temperatura_maxima:.1f}°C")
print(f"Temperatura mínima: {temperatura_minima:.1f}°C")
print(f"Temperatura desvio padrão: {temperatura_desv_padrao:.1f}°C")


Temperatura média: 20.0°C
Temperatura máxima: 36.7°C
Temperatura mínima: 0.5°C
Temperatura desvio padrão: 7.5°C


In [42]:
# Identificar dias com temperatura acima de 30°C (potencialmente prejudiciais para certas culturas)
dias_quentes = np.where(temp_array > 30)[0]
percentual_dias_quentes = len(dias_quentes) / dias * 100
print(f"Percentual de dias com temperatura acima de 30°C: {percentual_dias_quentes:.1f}%")


Percentual de dias com temperatura acima de 30°C: 10.1%


In [43]:
# Dividir em 12 meses usando array_split
temp_por_mes = np.array_split(temp_array, 12)

In [44]:

# Calcular médias mensais
media_mensal = np.array([np.mean(mes) for mes in temp_por_mes])

# Visualizar os resultados
meses = ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez']
print("\nTemperaturas médias mensais:")
for mes, temp in zip(meses, media_mensal):
    print(f"{mes}: {temp:.1f}°C")


Temperaturas médias mensais:
Jan: 21.9°C
Fev: 26.7°C
Mar: 29.7°C
Abr: 29.4°C
Mai: 26.5°C
Jun: 22.8°C
Jul: 17.7°C
Ago: 12.5°C
Set: 10.0°C
Out: 10.8°C
Nov: 13.9°C
Dez: 17.3°C


## Identificar o melhor mês para plantio (exemplo: temperatura ideal entre 18-25°C)

In [45]:

ideal_planting_condition = np.abs(media_mensal - 21.5)  # Distância da temp. ideal (21.5°C)
melhor_mes_plantio = meses[np.argmin(ideal_planting_condition)]
print(f"\nMelhor mês para plantio: {melhor_mes_plantio}")

# Detectar períodos de seca (exemplo: 7 dias consecutivos acima de 28°C)
periodos_seca = []
contador = 0

for i, temp in enumerate(temp_array):
    if temp > 28:
        contador += 1
    else:
        if contador >= 7:
            periodos_seca.append((i-contador, i-1))
        contador = 0

# Verificar se o último período é de seca
if contador >= 7:
    periodos_seca.append((dias-contador, dias-1))

print(f"\nPeríodos de seca (7+ dias acima de 28°C): {len(periodos_seca)}")
for inicio, fim in periodos_seca[:3]:  # Mostrar apenas os 3 primeiros períodos
    print(f"Dias {inicio+1} a {fim+1}: {fim-inicio+1} dias")


Melhor mês para plantio: Jan

Períodos de seca (7+ dias acima de 28°C): 1
Dias 86 a 92: 7 dias
